from horarios.views.views_actividades import *
from horarios.views.views_profesor import *
from horarios.views.views_alumnos import *
from horarios.views.views_asignatura import *
from horarios.views.views_atenciones import *
from horarios.views.views_sistema import *
from horarios.views.views_certificados import *
from horarios.views.views_consejo import *
from horarios.views.views_impresiones import *
from horarios.views.views_insumos import *
from horarios.views.views_prestamos import *
from horarios.views.views_horarios import *
from horarios.views.views_especialidad import *
from horarios.views.views_disponibilidad import *