# Generated by Django 5.0.1 on 2025-07-25 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('IdInsumo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('NombreInsumo', models.CharField(max_length=100)),
                ('DetalleInsumo', models.TextField(max_length=100)),
                ('StockInsumo', models.IntegerField(default=0)),
                ('Foto1Insumo', models.FileField(blank=True, null=True, upload_to='images/insumos/')),
                ('Foto2Insumo', models.FileField(blank=True, null=True, upload_to='images/insumos/')),
                ('Foto3Insumo', models.FileField(blank=True, null=True, upload_to='images/insumos/')),
                ('EstadoInsumo', models.CharField(choices=[('BUENO', 'BUENO'), ('MALO', 'MALO'), ('EN REPARACION', 'EN REPARACION')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('rut', models.TextField(max_length=100, unique=True)),
                ('nombre', models.TextField(max_length=100)),
                ('apellido', models.TextField(max_length=100)),
                ('nivel', models.CharField(default='BASICA y MEDIA', max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='images/profesores/')),
            ],
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Tipo', models.CharField(choices=[('ACT. RECREATIVA', 'ACT. RECREATIVA'), ('ACT. DE BAILE', 'ACT. DE BAILE'), ('ACT. DEPORTIVA', 'ACT. DEPORTIVA'), ('OTRA ACTIVIDAD', 'OTRA ACTIVIDAD')], max_length=50)),
                ('Nombre', models.CharField(blank=True, max_length=200)),
                ('FechaHoraRegistro', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraPlanificada', models.DateTimeField(blank=True)),
                ('Observacion', models.TextField(max_length=100)),
                ('Foto1', models.FileField(blank=True, null=True, upload_to='images/actividades/')),
                ('Foto2', models.FileField(blank=True, null=True, upload_to='images/actividades/')),
                ('Foto3', models.FileField(blank=True, null=True, upload_to='images/actividades/')),
                ('NumeroParticipantesActividad', models.IntegerField(default=0)),
                ('Profesor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('matricula', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('FechaHoraRegistroMatriculaEstudiante', models.DateTimeField(auto_now_add=True)),
                ('curso', models.CharField(choices=[('PREKINDER', 'PREKINDER'), ('KINDER', 'KINDER'), ('PRIMERO BASICO', 'PRIMERO BASICO'), ('SEGUNDO BASICO', 'SEGUNDO BASICO'), ('TERCERO BASICO', 'TERCERO BASICO'), ('CUARTO BASICO', 'CUARTO BASICO'), ('QUINTO BASICO', 'QUINTO BASICO'), ('SEXTO BASICO', 'SEXTO BASICO'), ('SEPTIMO BASICO', 'SEPTIMO BASICO'), ('OCTAVO BASICO', 'OCTAVO BASICO'), ('PRIMERO MEDIO', 'PRIMERO MEDIO'), ('SEGUNDO MEDIO', 'SEGUNDO MEDIO'), ('TERCERO MEDIO', 'TERCERO MEDIO'), ('CUARTO MEDIO', 'CUARTO MEDIO')], max_length=50)),
                ('run', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('direccion', models.CharField(default='-----', max_length=200)),
                ('comuna', models.CharField(choices=[('Antofagasta', 'Antofagasta'), ('Buin', 'Buin'), ('Calama', 'Calama'), ('Chépica', 'Chépica'), ('Chimbarongo', 'Chimbarongo'), ('Codegua', 'Codegua'), ('Coinco', 'Coinco'), ('Coltauco', 'Coltauco'), ('Colina', 'Colina'), ('Doñihue', 'Doñihue'), ('Graneros', 'Graneros'), ('Huechuraba', 'Huechuraba'), ('Isla de Maipo', 'Isla de Maipo'), ('Lampa', 'Lampa'), ('La Estrella', 'La Estrella'), ('Las Cabras', 'Las Cabras'), ('Litueche', 'Litueche'), ('Lolol', 'Lolol'), ('Lo Espejo', 'Lo Espejo'), ('Maipu', 'Maipu'), ('Machalí', 'Machalí'), ('Malloa', 'Malloa'), ('Marchihue', 'Marchihue'), ('Mostazal', 'Mostazal'), ('Nancagua', 'Nancagua'), ('Navidad', 'Navidad'), ('Olivar', 'Olivar'), ('Palmilla', 'Palmilla'), ('Paredones', 'Paredones'), ('Peralillo', 'Peralillo'), ('Peumo', 'Peumo'), ('Peñalolén', 'Peñalolén'), ('Pichidegua', 'Pichidegua'), ('Pichilemu', 'Pichilemu'), ('Placilla', 'Placilla'), ('Pumanque', 'Pumanque'), ('Quinta de Tilcoco', 'Quinta de Tilcoco'), ('Rancagua', 'Rancagua'), ('Renca', 'Renca'), ('Rengo', 'Rengo'), ('Requínoa', 'Requínoa'), ('San Fernando', 'San Fernando'), ('Santa Cruz', 'Santa Cruz'), ('San Vicente', 'San Vicente'), ('San Rosendo', 'San Rosendo'), ('Santiago', 'Santiago'), ('San Bernardo', 'San Bernardo'), ('San Carlos', 'San Carlos')], max_length=50)),
                ('procedencia', models.CharField(default='-----', max_length=150, null=True)),
                ('curso_repetido', models.CharField(choices=[('NO APLICA', 'NO APLICA'), ('PREKINDER', 'PREKINDER'), ('KINDER', 'KINDER'), ('PRIMERO BASICO', 'PRIMERO BASICO'), ('SEGUNDO BASICO', 'SEGUNDO BASICO'), ('TERCERO BASICO', 'TERCERO BASICO'), ('CUARTO BASICO', 'CUARTO BASICO'), ('QUINTO BASICO', 'QUINTO BASICO'), ('SEXTO BASICO', 'SEXTO BASICO'), ('SEPTIMO BASICO', 'SEPTIMO BASICO'), ('OCTAVO BASICO', 'OCTAVO BASICO'), ('PRIMERO MEDIO', 'PRIMERO MEDIO'), ('SEGUNDO MEDIO', 'SEGUNDO MEDIO'), ('TERCERO MEDIO', 'TERCERO MEDIO'), ('CUARTO MEDIO', 'CUARTO MEDIO')], default='NO APLICA', max_length=50)),
                ('con_quien_vive', models.CharField(default='-----', max_length=100)),
                ('enfermedad', models.CharField(default='-----', max_length=120, null=True)),
                ('prevision', models.CharField(choices=[('Isapre', 'Isapre'), ('Fonasa', 'Fonasa'), ('Ninguna', 'Ninguna')], default='Ninguna', max_length=20)),
                ('letra_fonasa', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('NO APLICA', 'NO APLICA')], default='NO APLICA', max_length=10)),
                ('alimentacion_establecimiento', models.CharField(choices=[('Si', 'Si'), ('No', 'No'), ('No sabe', 'No sabe')], default='No sabe', max_length=8)),
                ('programa_solidario', models.CharField(choices=[('Si', 'Si'), ('No', 'No'), ('No sabe', 'No sabe')], default='No sabe', max_length=7)),
                ('programa', models.CharField(default='-----', max_length=150, null=True)),
                ('locomocion', models.CharField(default='-----', max_length=50)),
                ('fono_locomocion', models.CharField(default='9', max_length=9, null=True)),
                ('vive_con', models.CharField(default='-----', max_length=150)),
                ('emergencia', models.CharField(default='-----', max_length=50)),
                ('complementarios', models.CharField(blank=True, max_length=200)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='images/estudiantes/')),
                ('Administrativo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('run', models.CharField(blank=True, max_length=12)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=50)),
                ('apellido_materno', models.CharField(blank=True, max_length=50)),
                ('fono', models.CharField(blank=True, default='9', max_length=9)),
                ('escolaridad', models.CharField(blank=True, choices=[('SIN ESTUDIOS', 'SIN ESTUDIOS'), ('BASICA INCOMPLETA', 'BASICA INCOMPLETA'), ('BASICA COMPLETA', 'BASICA COMPLETA'), ('MEDIA INCOMPLETA', 'MEDIA INCOMPLETA'), ('MEDIA COMPLETA', 'MEDIA COMPLETA'), ('ESTUDIOS SUPERIORES INCOMPLETA', 'ESTUDIOS SUPERIORES INCOMPLETA'), ('ESTUDIOS SUPERIORES COMPLETA', 'ESTUDIOS SUPERIORES COMPLETA')], max_length=32)),
                ('ocupacion', models.CharField(blank=True, default='No aplica', max_length=100)),
                ('edad', models.IntegerField(blank=True)),
                ('religion', models.CharField(blank=True, default='No aplica', max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Apoderados', to='horarios.alumnos')),
            ],
        ),
        migrations.CreateModel(
            name='Atenciones',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Tipo', models.CharField(choices=[('ATENCION MEDICA O ENFERMERIA', 'ATENCION MEDICA O ENFERMERIA'), ('ATENCION NUTRICIONAL', 'ATENCION NUTRICIONAL'), ('ATENCION PSICOPEDAGOGICA', 'ATENCION PSICOPEDAGOGICA'), ('ATENCION SOCIAL', 'ATENCION SOCIAL'), ('ORIENTACION VOCACIONAL', 'ORIENTACION VOCACIONAL'), ('PSICOLOGICA', 'PSICOLOGICA'), ('PEDAGOGICA', 'PEDAGOGICA')], max_length=50)),
                ('FechaHoraRegistro', models.DateTimeField(auto_now_add=True)),
                ('Motivo', models.TextField(choices=[('CITACION', 'CITACION'), ('DESCONPENSACION', 'DESCONPENSACION'), ('URGENCIA', 'URGENCIA'), ('SOLICITUD', 'SOLICITUD'), ('OTRA', 'OTRA')], max_length=100)),
                ('Observaciones', models.TextField()),
                ('Foto1Evidencia', models.FileField(blank=True, null=True, upload_to='images/atenciones/')),
                ('Foto2Evidencia', models.FileField(blank=True, null=True, upload_to='images/atenciones/')),
                ('Foto3Evidencia', models.FileField(blank=True, null=True, upload_to='images/atenciones/')),
                ('Profesional', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idMatricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.alumnos')),
            ],
        ),
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('idCertificado', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('TipoCertificado', models.CharField(choices=[('CERTIFICADO DE ENSEÑANZA BASICA', 'CERTIFICADO DE ENSEÑANZA BASICA'), ('CERTIFICADO DE ENSEÑANZA MEDIA', 'CERTIFICADO DE ENSEÑANZA MEDIA'), ('CERTIFICADO DE NOTAS(CONCENTRACION DE NOTAS)', 'CERTIFICADO DE NOTAS(CONCENTRACION DE NOTAS)'), ('CERTIFICADO DE ALUMNO REGULAR', 'CERTIFICADO DE ALUMNO REGULAR'), ('CERTIFICADO DE CONDUCTA', 'CERTIFICADO DE CONDUCTA'), ('CERTIFICADO DE PARTICIPACION EN ACTIVIDADES EXTRACURRICULARES', 'CERTIFICADO DE PARTICIPACION EN ACTIVIDADES EXTRACURRICULARES')], max_length=100)),
                ('MotivoCertificado', models.CharField(max_length=200)),
                ('LugarPresentacionCertificado', models.CharField(max_length=200)),
                ('FechaHoraRegistroCertificado', models.DateTimeField(auto_now_add=True)),
                ('EstadoCertificado', models.CharField(choices=[('RETIRADO', 'RETIRADO'), ('SIN ENTREGAR', 'SIN ENTREGAR'), ('PENDIENTE', 'PENDIENTE')], default='PENDIENTE', max_length=50)),
                ('Administrativo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idMatricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.alumnos')),
            ],
        ),
        migrations.CreateModel(
            name='ConsejosProfesores',
            fields=[
                ('idConsejo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('FechaHoraRegistroConsejo', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraPlanificadaConsejo', models.DateTimeField(blank=True)),
                ('ComentariosConsejo', models.TextField(max_length=100)),
                ('AcuerdosConsejo', models.TextField()),
                ('Archivo1Consejo', models.FileField(blank=True, null=True, upload_to='images/consejos/')),
                ('Archivo2Consejo', models.FileField(blank=True, null=True, upload_to='images/consejos/')),
                ('Archivo3Consejo', models.FileField(blank=True, null=True, upload_to='images/consejos/')),
                ('NumeroProfesoresConsejo', models.IntegerField(default=0)),
                ('Administrativo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('codigo', models.TextField(max_length=100)),
                ('nombre', models.CharField(choices=[('Artes (3ero y 4to Medio) - 2hrs', 'Artes (3ero y 4to Medio) - 2hrs'), ('Artes Visuales (1ero a 4to Basico) - 2hrs', 'Artes Visuales (1ero a 4to Basico) - 2hrs'), ('Artes Visuales (5to a 6to Basico) - 1hr', 'Artes Visuales (5to a 6to Basico) - 1hr'), ('Artes Visuales o Música (1ero y 2do Medio) - 2hrs', 'Artes Visuales o Música (1ero y 2do Medio) - 2hrs'), ('Artes Visuales y Música (7mo y 8vo Basico) - 2hrs', 'Artes Visuales y Música (7mo y 8vo Basico) - 2hrs'), ('Asignatura Kinder - 1hr', 'Asignatura Kinder - 1hr'), ('Asignatura PreKinder - 1hr', 'Asignatura PreKinder - 1hr'), ('Ciencias Naturales  (1ero y 2do Medio) - 6hrs', 'Ciencias Naturales  (1ero y 2do Medio) - 6hrs'), ('Ciencias Naturales  (7mo y 8vo Basico) - 4hrs', 'Ciencias Naturales  (7mo y 8vo Basico) - 4hrs'), ('Ciencias Naturales (1ero a 6to Basico) - 3hrs', 'Ciencias Naturales (1ero a 6to Basico) - 3hrs'), ('Ciencias para la Ciudadanía (3ero y 4to Medio) - 2hrs', 'Ciencias para la Ciudadanía (3ero y 4to Medio) - 2hrs'), ('Educación Ciudadana (3ero y 4to Medio) - 2hrs', 'Educación Ciudadana (3ero y 4to Medio) - 2hrs'), ('Educación Física y Salud  (Todas) - 2hrs', 'Educación Física y Salud  (Todas) - 2hrs'), ('Electivo de biología (3ero y 4to Medio) - 6hrs', 'Electivo de biología (3ero y 4to Medio) - 6hrs'), ('Electivo de matematicas (3ero y 4to Medio) - 6hrs', 'Electivo de matematicas (3ero y 4to Medio) - 6hrs'), ('Electivo de historia (3ero y 4to Medio) - 6hrs', 'Electivo de historia (3ero y 4to Medio) - 6hrs'), ('Electivo de lengua y literatura (3ero y 4to Medio) - 6hrs', 'Electivo de lengua y literatura (3ero y 4to Medio) - 6hrs'), ('Filosofía (3ero y 4to Medio) - 2hrs', 'Filosofía (3ero y 4to Medio) - 2hrs'), ('Historia, Geografía y Ciencias Sociales  (5to a 2do Medio) - 4hrs', 'Historia, Geografía y Ciencias Sociales  (5to a 2do Medio) - 4hrs'), ('Historia, Geografía y Ciencias Sociales (1ero a 4to Basico) - 3hrs', 'Historia, Geografía y Ciencias Sociales (1ero a 4to Basico) - 3hrs'), ('Historia, Geografía y Ciencias Sociales (3ero y 4to Medio) - 2hrs', 'Historia, Geografía y Ciencias Sociales (3ero y 4to Medio) - 2hrs'), ('Idioma Extranjero: Inglés  (5to a 2do medio) - 3hrs', 'Idioma Extranjero: Inglés  (5to a 2do medio) - 3hrs'), ('Inglés (3ero y 4to Medio) - 2hrs', 'Inglés (3ero y 4to Medio) - 2hrs'), ('Inglés (Libre Disposicion)  (1ero a 4to Basico) - 1hr', 'Inglés (Libre Disposicion)  (1ero a 4to Basico) - 1hr'), ('Inglés Nivel Transicion (Prekinder y Kinder) - 1hr', 'Inglés Nivel Transicion (Prekinder y Kinder) - 1hr'), ('Lengua y Literatura (3ero y 4to Medio) - 3hrs', 'Lengua y Literatura (3ero y 4to Medio) - 3hrs'), ('Lengua y Literatura (7mo a 2do Medio) - 6hrs', 'Lengua y Literatura (7mo a 2do Medio) - 6hrs'), ('Lenguaje y Comunicación  (5to y 6to Basico) - 6hrs', 'Lenguaje y Comunicación  (5to y 6to Basico) - 6hrs'), ('Lenguaje y Comunicación (1ero a 4to Basico) - 8hrs', 'Lenguaje y Comunicación (1ero a 4to Basico) - 8hrs'), ('Matemática  (1ero Basico a 2do Medio) - 6hrs', 'Matemática  (1ero Basico a 2do Medio) - 6hrs'), ('Matemática  (3ero y 4to Medio) - 3hrs', 'Matemática  (3ero y 4to Medio) - 3hrs'), ('Música  (1ero a 4to Basico) - 2hrs', 'Música  (1ero a 4to Basico) - 2hrs'), ('Música  (5to y 6to Basico) - 1hr', 'Música  (5to y 6to Basico) - 1hr'), ('Orientación  (1ero a 4to Basico) - 1hr', 'Orientación  (1ero a 4to Basico) - 1hr'), ('Orientación  (5to a 2do Medio) - 1hr', 'Orientación  (5to a 2do Medio) - 1hr'), ('Religión (Todas) - 2hrs', 'Religión (Todas) - 2hrs'), ('Tecnología  (1ero a 4to Basico) - 1hr', 'Tecnología  (1ero a 4to Basico) - 1hr'), ('Tecnología  (5to a 2do Medio) - 1hr', 'Tecnología  (5to a 2do Medio) - 1hr')], max_length=100)),
                ('nivel', models.CharField(choices=[('BASICA', 'BASICA'), ('MEDIA', 'MEDIA'), ('PREBASICA', 'PREBASICA')], max_length=100)),
                ('bloques', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Impresiones',
            fields=[
                ('idImpresion', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('FechaHoraRegistroImpresion', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraUtilizacionImpresion', models.DateTimeField(blank=True)),
                ('CursoImpresion', models.CharField(choices=[('PREKINDER', 'PREKINDER'), ('KINDER', 'KINDER'), ('PRIMERO BASICO', 'PRIMERO BASICO'), ('SEGUNDO BASICO', 'SEGUNDO BASICO'), ('TERCERO BASICO', 'TERCERO BASICO'), ('CUARTO BASICO', 'CUARTO BASICO'), ('QUINTO BASICO', 'QUINTO BASICO'), ('SEXTO BASICO', 'SEXTO BASICO'), ('SEPTIMO BASICO', 'SEPTIMO BASICO'), ('OCTAVO BASICO', 'OCTAVO BASICO'), ('PRIMERO MEDIO', 'PRIMERO MEDIO'), ('SEGUNDO MEDIO', 'SEGUNDO MEDIO'), ('TERCERO MEDIO', 'TERCERO MEDIO'), ('CUARTO MEDIO', 'CUARTO MEDIO')], max_length=50)),
                ('AsignaturaImpresion', models.CharField(max_length=50)),
                ('Archivo1Impresion', models.FileField(blank=True, null=True, upload_to='images/impresiones/')),
                ('Archivo2Impresion', models.FileField(blank=True, null=True, upload_to='images/impresiones/')),
                ('Archivo3Impresion', models.FileField(blank=True, null=True, upload_to='images/impresiones/')),
                ('ObservacionImpresion', models.TextField()),
                ('EstadoImpresion', models.CharField(choices=[('REALIZADO', 'REALIZADO'), ('PENDIENTE', 'PENDIENTE'), ('ERROR', 'ERROR')], default='PENDIENTE', max_length=50)),
                ('ProfesorImpresion', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('es_madre', models.BooleanField()),
                ('run', models.CharField(blank=True, max_length=12)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=50)),
                ('apellido_materno', models.CharField(blank=True, max_length=50)),
                ('fono', models.CharField(blank=True, default='9', max_length=9)),
                ('escolaridad', models.CharField(blank=True, choices=[('SIN ESTUDIOS', 'SIN ESTUDIOS'), ('BASICA INCOMPLETA', 'BASICA INCOMPLETA'), ('BASICA COMPLETA', 'BASICA COMPLETA'), ('MEDIA INCOMPLETA', 'MEDIA INCOMPLETA'), ('MEDIA COMPLETA', 'MEDIA COMPLETA'), ('ESTUDIOS SUPERIORES INCOMPLETA', 'ESTUDIOS SUPERIORES INCOMPLETA'), ('ESTUDIOS SUPERIORES COMPLETA', 'ESTUDIOS SUPERIORES COMPLETA')], max_length=32)),
                ('ocupacion', models.CharField(blank=True, default='No aplica', max_length=100)),
                ('edad', models.IntegerField(blank=True)),
                ('religion', models.CharField(blank=True, default='No aplica', max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Padres', to='horarios.alumnos')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('IdPrestamo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('FechaHoraRegistroPrestamo', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraDevolucionPrestamo', models.DateTimeField(blank=True)),
                ('DetallePrestamo', models.TextField(max_length=100)),
                ('FotoPrestamo', models.FileField(blank=True, null=True, upload_to='images/prestamos/')),
                ('EstadoPrestamo', models.CharField(choices=[('SIN DEVOLVER', 'SIN DEVOLVER'), ('DEVUELTO', 'DEVUELTO')], default='SIN DEVOLVER', max_length=50)),
                ('Administrativo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('bloque', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)])),
                ('dia', models.TextField(choices=[('LUNES', 'LUNES'), ('MARTES', 'MARTES'), ('MIERCOLES', 'MIERCOLES'), ('JUEVES', 'JUEVES'), ('VIERNES', 'VIERNES')], max_length=100)),
                ('asignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horarios.asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.curso')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horarios.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='DisponibilidadProfesor',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('bloque', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)])),
                ('dia', models.TextField(choices=[('LUNES', 'LUNES'), ('MARTES', 'MARTES'), ('MIERCOLES', 'MIERCOLES'), ('JUEVES', 'JUEVES'), ('VIERNES', 'VIERNES')], max_length=100)),
                ('estado', models.TextField(choices=[('DISPONIBLE', 'DISPONIBLE'), ('NO DISPONIBLE', 'NO DISPONIBLE')], default='NO DISPONIBLE', max_length=100)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='AsignaturasProfesor',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(choices=[('Artes (3ero y 4to Medio) - 2hrs', 'Artes (3ero y 4to Medio) - 2hrs'), ('Artes Visuales (1ero a 4to Basico) - 2hrs', 'Artes Visuales (1ero a 4to Basico) - 2hrs'), ('Artes Visuales (5to a 6to Basico) - 1hr', 'Artes Visuales (5to a 6to Basico) - 1hr'), ('Artes Visuales o Música (1ero y 2do Medio) - 2hrs', 'Artes Visuales o Música (1ero y 2do Medio) - 2hrs'), ('Artes Visuales y Música (7mo y 8vo Basico) - 2hrs', 'Artes Visuales y Música (7mo y 8vo Basico) - 2hrs'), ('Asignatura Kinder - 1hr', 'Asignatura Kinder - 1hr'), ('Asignatura PreKinder - 1hr', 'Asignatura PreKinder - 1hr'), ('Ciencias Naturales  (1ero y 2do Medio) - 6hrs', 'Ciencias Naturales  (1ero y 2do Medio) - 6hrs'), ('Ciencias Naturales  (7mo y 8vo Basico) - 4hrs', 'Ciencias Naturales  (7mo y 8vo Basico) - 4hrs'), ('Ciencias Naturales (1ero a 6to Basico) - 3hrs', 'Ciencias Naturales (1ero a 6to Basico) - 3hrs'), ('Ciencias para la Ciudadanía (3ero y 4to Medio) - 2hrs', 'Ciencias para la Ciudadanía (3ero y 4to Medio) - 2hrs'), ('Educación Ciudadana (3ero y 4to Medio) - 2hrs', 'Educación Ciudadana (3ero y 4to Medio) - 2hrs'), ('Educación Física y Salud  (Todas) - 2hrs', 'Educación Física y Salud  (Todas) - 2hrs'), ('Electivo de biología (3ero y 4to Medio) - 6hrs', 'Electivo de biología (3ero y 4to Medio) - 6hrs'), ('Electivo de matematicas (3ero y 4to Medio) - 6hrs', 'Electivo de matematicas (3ero y 4to Medio) - 6hrs'), ('Electivo de historia (3ero y 4to Medio) - 6hrs', 'Electivo de historia (3ero y 4to Medio) - 6hrs'), ('Electivo de lengua y literatura (3ero y 4to Medio) - 6hrs', 'Electivo de lengua y literatura (3ero y 4to Medio) - 6hrs'), ('Filosofía (3ero y 4to Medio) - 2hrs', 'Filosofía (3ero y 4to Medio) - 2hrs'), ('Historia, Geografía y Ciencias Sociales  (5to a 2do Medio) - 4hrs', 'Historia, Geografía y Ciencias Sociales  (5to a 2do Medio) - 4hrs'), ('Historia, Geografía y Ciencias Sociales (1ero a 4to Basico) - 3hrs', 'Historia, Geografía y Ciencias Sociales (1ero a 4to Basico) - 3hrs'), ('Historia, Geografía y Ciencias Sociales (3ero y 4to Medio) - 2hrs', 'Historia, Geografía y Ciencias Sociales (3ero y 4to Medio) - 2hrs'), ('Idioma Extranjero: Inglés  (5to a 2do medio) - 3hrs', 'Idioma Extranjero: Inglés  (5to a 2do medio) - 3hrs'), ('Inglés (3ero y 4to Medio) - 2hrs', 'Inglés (3ero y 4to Medio) - 2hrs'), ('Inglés (Libre Disposicion)  (1ero a 4to Basico) - 1hr', 'Inglés (Libre Disposicion)  (1ero a 4to Basico) - 1hr'), ('Inglés Nivel Transicion (Prekinder y Kinder) - 1hr', 'Inglés Nivel Transicion (Prekinder y Kinder) - 1hr'), ('Lengua y Literatura (3ero y 4to Medio) - 3hrs', 'Lengua y Literatura (3ero y 4to Medio) - 3hrs'), ('Lengua y Literatura (7mo a 2do Medio) - 6hrs', 'Lengua y Literatura (7mo a 2do Medio) - 6hrs'), ('Lenguaje y Comunicación  (5to y 6to Basico) - 6hrs', 'Lenguaje y Comunicación  (5to y 6to Basico) - 6hrs'), ('Lenguaje y Comunicación (1ero a 4to Basico) - 8hrs', 'Lenguaje y Comunicación (1ero a 4to Basico) - 8hrs'), ('Matemática  (1ero Basico a 2do Medio) - 6hrs', 'Matemática  (1ero Basico a 2do Medio) - 6hrs'), ('Matemática  (3ero y 4to Medio) - 3hrs', 'Matemática  (3ero y 4to Medio) - 3hrs'), ('Música  (1ero a 4to Basico) - 2hrs', 'Música  (1ero a 4to Basico) - 2hrs'), ('Música  (5to y 6to Basico) - 1hr', 'Música  (5to y 6to Basico) - 1hr'), ('Orientación  (1ero a 4to Basico) - 1hr', 'Orientación  (1ero a 4to Basico) - 1hr'), ('Orientación  (5to a 2do Medio) - 1hr', 'Orientación  (5to a 2do Medio) - 1hr'), ('Religión (Todas) - 2hrs', 'Religión (Todas) - 2hrs'), ('Tecnología  (1ero a 4to Basico) - 1hr', 'Tecnología  (1ero a 4to Basico) - 1hr'), ('Tecnología  (5to a 2do Medio) - 1hr', 'Tecnología  (5to a 2do Medio) - 1hr')], max_length=100)),
                ('nivel', models.TextField(default='BASICA y MEDIA', max_length=100)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
                ('cargo', models.CharField(choices=[('DIRECTOR', 'DIRECTOR'), ('ADMINISTRADOR', 'ADMINISTRADOR'), ('PROFESOR', 'PROFESOR'), ('ESTUDIANTE', 'ESTUDIANTE')], default='ESTUDIANTE', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateTimeField()),
                ('accion', models.TextField(max_length=200)),
                ('tabla', models.TextField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.usuario')),
            ],
        ),
    ]
