# Generated by Django 5.0.1 on 2025-08-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
