# Generated by Django 5.2.3 on 2025-11-23 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0004_profesor_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='Administrativo',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos_administrativo', to=settings.AUTH_USER_MODEL),
        ),
    ]
