# Generated by Django 5.0.1 on 2025-12-13 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0006_actividades_habilitado_apoderado_habilitado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('evaluacion', models.CharField(max_length=100)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.alumnos')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.curso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.profesor')),
            ],
            options={
                'unique_together': {('alumno', 'asignatura', 'evaluacion')},
            },
        ),
    ]
