# Generated by Django 5.0.1 on 2025-12-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0007_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='DetallePrestamo',
            field=models.TextField(max_length=500),
        ),
    ]
