# Generated by Django 5.0.1 on 2025-12-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0008_alter_prestamos_detalleprestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='EstadoPrestamo',
            field=models.CharField(choices=[('SIN DEVOLVER', 'SIN DEVOLVER'), ('DEVUELTO', 'DEVUELTO'), ('VENCIDO', 'VENCIDO')], default='SIN DEVOLVER', max_length=50),
        ),
    ]
